//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMonitorWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppEvent
    {
        public int Id { get; set; }
        public string Host { get; set; }
        public string User { get; set; }
        public string Guid { get; set; }
        public System.DateTime DetectDT { get; set; }
        public Nullable<System.DateTime> IsLostDT { get; set; }
        public string AppTitle { get; set; }
        public Nullable<long> WorkingTime { get; set; }
    }
}
